- name: deploy DGS Process
  hosts: workflow-server
  become: yes
  become_user: root

  vars:
    vault_url: https://vault.itc.kfupm.edu.sa

  vars_prompt:
    - name: ad_username
      prompt: Your Active Directory username
      private: no

    - name: ad_password
      prompt: Your Active Directory password
      private: yes

  # tasks to be performed before role tasks, if any
  pre_tasks:

    - name: Vault authentication
      uri:
        url: "{{ vault_url }}/v1/auth/ldap/login/{{ ad_username }}"
        method: POST
        body: {"password": "{{ ad_password }}"}
        body_format: json
        validate_certs: no
      connection: local
      become: no
      register: auth

    # - name: Retrieve Adwar api password
    #   uri:
    #     url: "{{ vault_url }}/v1/secret/{{ env }}/operations/apps/course-specifications/staff_webservice_password"
    #     HEADER_X-Vault-Token: "{{ auth.json.auth.client_token }}"
    #     validate_certs: no
    #   connection: local
    #   become: no
    #   register: adwar_webservice_password

    # - name: Retrieve staff web service password
    #   uri:
    #     url: "{{ vault_url }}/v1/secret/{{ env }}/operations/apps/course-specifications/adwar_webservice_password"
    #     HEADER_X-Vault-Token: "{{ auth.json.auth.client_token }}"
    #     validate_certs: no
    #   connection: local
    #   become: no
    #   register: staff_webservice_password

    # - name: Retrieve email password
    #   uri:
    #     url: "{{ vault_url }}/v1/secret/{{ env }}/email/apps/course_cpecification_process/email_password"
    #     HEADER_X-Vault-Token: "{{ auth.json.auth.client_token }}"
    #     validate_certs: no
    #   connection: local
    #   become: no
    #   register: email_password

    # - name: Generate workflow properties
    #   set_fact:
    #     process_config_file: "{{ lookup('template', 'config.properties.j2') }}"

  roles:

    - name: camunda-project
      camunda_process_name: "course_specification_process"
      process_config_file: "{{ lookup('template', 'config.properties.j2') }}"