# Generated by Django 2.1 on 2019-05-20 11:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='mode_of_instruction_comments',
            field=models.TextField(blank=True, null=True, verbose_name='Mode Of Instruction Comments'),
        ),
        migrations.AlterField(
            model_name='course',
            name='mode_of_instruction_other',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(100)], verbose_name='Mode Of Instruction (Other) %'),
        ),
        migrations.AlterField(
            model_name='course',
            name='number',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator('\\d\\d\\d')], verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='course',
            name='weekly_office_hours',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(3)], verbose_name='Weekly Office Hours'),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='mode_of_instruction_comments',
            field=models.TextField(blank=True, null=True, verbose_name='Mode Of Instruction Comments'),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='mode_of_instruction_other',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(100)], verbose_name='Mode Of Instruction (Other) %'),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='number',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator('\\d\\d\\d')], verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='weekly_office_hours',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(3)], verbose_name='Weekly Office Hours'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('program_code', 'number')},
        ),
    ]
