# Generated by Django 2.1 on 2019-06-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20190520_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='other_contact_hours',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Other Contact Hours'),
        ),
        migrations.AddField(
            model_name='course',
            name='other_contact_hours_description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Other Contact Hours Description'),
        ),
        migrations.AddField(
            model_name='course',
            name='practical_contact_hours',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Practical Contact Hours'),
        ),
        migrations.AddField(
            model_name='course',
            name='tutorial_contact_hours',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Tutorial Contact Hours'),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='other_contact_hours',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Other Contact Hours'),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='other_contact_hours_description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Other Contact Hours Description'),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='practical_contact_hours',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Practical Contact Hours'),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='tutorial_contact_hours',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Tutorial Contact Hours'),
        ),
    ]
