# Generated by Django 2.1 on 2019-06-12 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20190609_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='engineering_credit_hours',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Engineering Credit Hours'),
        ),
        migrations.AlterField(
            model_name='course',
            name='general_education_credit_hours',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='General Education Credit Hours'),
        ),
        migrations.AlterField(
            model_name='course',
            name='humanities_credit_hours',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Humanities Credit Hours'),
        ),
        migrations.AlterField(
            model_name='course',
            name='math_science_credit_hours',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Mathematics/Science Credit Hours'),
        ),
        migrations.AlterField(
            model_name='course',
            name='other_subject_areas_credit_hours',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Other Subject Areas Credit Hours'),
        ),
        migrations.AlterField(
            model_name='course',
            name='self_study_lab',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Self-Study Laboratory Hours'),
        ),
        migrations.AlterField(
            model_name='course',
            name='self_study_lecture',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Self-Study Lecture Hours'),
        ),
        migrations.AlterField(
            model_name='course',
            name='self_study_other',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Self-Study Other Hours'),
        ),
        migrations.AlterField(
            model_name='course',
            name='self_study_practical',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Self-Study Practical Hours'),
        ),
        migrations.AlterField(
            model_name='course',
            name='self_study_tutorial',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Self-Study Tutorial Hours'),
        ),
        migrations.AlterField(
            model_name='course',
            name='social_sciences_credit_hours',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Social Sciences Credit Hours'),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='engineering_credit_hours',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Engineering Credit Hours'),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='general_education_credit_hours',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='General Education Credit Hours'),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='humanities_credit_hours',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Humanities Credit Hours'),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='math_science_credit_hours',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Mathematics/Science Credit Hours'),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='other_subject_areas_credit_hours',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Other Subject Areas Credit Hours'),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='self_study_lab',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Self-Study Laboratory Hours'),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='self_study_lecture',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Self-Study Lecture Hours'),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='self_study_other',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Self-Study Other Hours'),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='self_study_practical',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Self-Study Practical Hours'),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='self_study_tutorial',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Self-Study Tutorial Hours'),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='social_sciences_credit_hours',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Social Sciences Credit Hours'),
        ),
    ]
