# Generated by Django 2.1 on 2019-06-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20190612_1027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessmenttask',
            options={'ordering': ('course', 'type', 'week_due')},
        ),
        migrations.AlterField(
            model_name='assessmenttask',
            name='week_due',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Week Due'),
        ),
        migrations.AlterField(
            model_name='historicalassessmenttask',
            name='week_due',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Week Due'),
        ),
    ]
