# Generated by Django 2.1 on 2019-06-27 09:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20190627_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmenttask',
            name='week_due',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(17)], verbose_name='Week Due'),
        ),
        migrations.AlterField(
            model_name='course',
            name='engineering_credit_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Engineering / Computer Science Credit Hours'),
        ),
        migrations.AlterField(
            model_name='historicalassessmenttask',
            name='week_due',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(17)], verbose_name='Week Due'),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='engineering_credit_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Engineering / Computer Science Credit Hours'),
        ),
    ]
