# Generated by Django 2.1 on 2019-07-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20190627_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserelease',
            name='approved_by',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Approved By'),
        ),
        migrations.AddField(
            model_name='courserelease',
            name='approved_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approved On'),
        ),
    ]
