# Generated by Django 2.1 on 2019-07-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20190703_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserelease',
            name='approved',
            field=models.NullBooleanField(verbose_name='Approved'),
        ),
    ]
