# Generated by Django 2.1 on 2019-07-28 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0011_courserelease_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=200)),
                ('comment', models.CharField(max_length=1000)),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('commented_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_comments', to=settings.AUTH_USER_MODEL, verbose_name='Commenter')),
            ],
        ),
        migrations.AlterModelOptions(
            name='courserelease',
            options={'get_latest_by': ['course__history_date', 'version']},
        ),
        migrations.AddField(
            model_name='courserelease',
            name='_workflow_status',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Workflow Status (Cached)'),
        ),
        migrations.AddField(
            model_name='courserelease',
            name='workflow_instance_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Workflow Instance ID'),
        ),
        migrations.AlterField(
            model_name='courserelease',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_courses', to=settings.AUTH_USER_MODEL, verbose_name='Approved By'),
        ),
        migrations.AddField(
            model_name='approvalcomments',
            name='course_release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_comments', to='main_app.CourseRelease', verbose_name='course_release'),
        ),
    ]
