# Generated by Django 2.1 on 2019-10-06 08:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0012_auto_20190728_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsViews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_new', models.BooleanField(default=True, help_text='If checked, it means this comment is new to this user. The comment will be considered old, if the user moved on in the process to the next step', verbose_name='Is New?')),
                ('viewed_on', models.DateTimeField(auto_now=True, verbose_name='Viewed On')),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_views', to='main_app.ApprovalComments', verbose_name='Comment')),
                ('viewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viewed_comments', to=settings.AUTH_USER_MODEL, verbose_name='Viewer')),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='number',
            field=models.CharField(max_length=10, null=True, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='course',
            name='program_code',
            field=models.CharField(help_text='3 or 4 upper-case letters only', max_length=10, null=True, validators=[django.core.validators.RegexValidator('^[A-Z]{3,4}$')], verbose_name='Program Code'),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='number',
            field=models.CharField(max_length=10, null=True, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='program_code',
            field=models.CharField(help_text='3 or 4 upper-case letters only', max_length=10, null=True, validators=[django.core.validators.RegexValidator('^[A-Z]{3,4}$')], verbose_name='Program Code'),
        ),
    ]
