# Generated by Django 2.1 on 2019-10-08 10:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0013_auto_20191006_1159'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApprovalComments',
            new_name='ApprovalComment',
        ),
        migrations.RenameModel(
            old_name='CommentsViews',
            new_name='CommentViewership',
        ),
        migrations.AlterModelOptions(
            name='approvalcomment',
            options={'get_latest_by': ['comment_date']},
        ),
    ]
