# Generated by Django 2.1 on 2019-10-07 08:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0013_auto_20191006_1159'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentsViews',
            new_name='CommentViewership',
        ),
        migrations.AlterModelOptions(
            name='approvalcomments',
            options={'get_latest_by': ['comment_date']},
        ),
        migrations.AddField(
            model_name='courserelease',
            name='_workflow_assignee',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Workflow Assignee (Cached)'),
        ),
    ]
