# Generated by Django 2.1 on 2019-10-07 08:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0014_auto_20191008_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserelease',
            name='_workflow_assignee',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Workflow Assignee (Cached)'),
        ),
    ]
