# Generated by Django 2.2.6 on 2019-10-21 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_20191009_1713'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courserelease',
            unique_together=set(),
        ),
    ]
