# Generated by Django 2.2.6 on 2019-10-27 11:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_auto_20191021_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmenttask',
            name='week_due',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(17)], verbose_name='Week Due'),
        ),
        migrations.AlterField(
            model_name='historicalassessmenttask',
            name='week_due',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(17)], verbose_name='Week Due'),
        ),
    ]
