# Generated by Django 2.2.6 on 2019-11-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_auto_20191027_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='not_to_be_taken_with_courses',
            field=models.ManyToManyField(blank=True, related_name='not_to_be_taken_with', to='main_app.Course'),
        ),
        migrations.AddField(
            model_name='courserelease',
            name='not_to_be_taken_with_courses',
            field=models.ManyToManyField(related_name='not_to_be_taken_with', to='main_app.HistoricalCourse'),
        ),
    ]
