# Generated by Django 2.2.6 on 2019-11-17 09:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_auto_20191105_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='catalog_description',
            field=models.TextField(help_text='General description of the course (Bulletin description)', null=True, verbose_name='Catalog Description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='program_code',
            field=models.CharField(help_text='2 or 4 upper-case letters only', max_length=10, null=True, validators=[django.core.validators.RegexValidator('^[A-Z]{2,4}$')], verbose_name='Program Code'),
        ),
        migrations.AlterField(
            model_name='course',
            name='required_textbooks_from_sierra',
            field=models.CharField(blank=True, help_text='List of required textbooks from Sierra system', max_length=1000, null=True, verbose_name='required_textbooks'),
        ),
        migrations.AlterField(
            model_name='course',
            name='social_sciences_credit_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Social Sciences and Business Credit Hours'),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='catalog_description',
            field=models.TextField(help_text='General description of the course (Bulletin description)', null=True, verbose_name='Catalog Description'),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='program_code',
            field=models.CharField(help_text='2 or 4 upper-case letters only', max_length=10, null=True, validators=[django.core.validators.RegexValidator('^[A-Z]{2,4}$')], verbose_name='Program Code'),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='required_textbooks_from_sierra',
            field=models.CharField(blank=True, help_text='List of required textbooks from Sierra system', max_length=1000, null=True, verbose_name='required_textbooks'),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='social_sciences_credit_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Social Sciences and Business Credit Hours'),
        ),
    ]
