# Generated by Django 2.2.6 on 2019-11-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_auto_20191117_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='self_study_lab',
        ),
        migrations.RemoveField(
            model_name='course',
            name='self_study_lecture',
        ),
        migrations.RemoveField(
            model_name='course',
            name='self_study_other',
        ),
        migrations.RemoveField(
            model_name='course',
            name='self_study_practical',
        ),
        migrations.RemoveField(
            model_name='course',
            name='self_study_tutorial',
        ),
        migrations.RemoveField(
            model_name='historicalcourse',
            name='self_study_lab',
        ),
        migrations.RemoveField(
            model_name='historicalcourse',
            name='self_study_lecture',
        ),
        migrations.RemoveField(
            model_name='historicalcourse',
            name='self_study_other',
        ),
        migrations.RemoveField(
            model_name='historicalcourse',
            name='self_study_practical',
        ),
        migrations.RemoveField(
            model_name='historicalcourse',
            name='self_study_tutorial',
        ),
        migrations.AddField(
            model_name='course',
            name='self_learning_assignments',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Self-Learning Assignments Hours'),
        ),
        migrations.AddField(
            model_name='course',
            name='self_learning_library',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Self-Learning Library Hours'),
        ),
        migrations.AddField(
            model_name='course',
            name='self_learning_other',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Self-Learning Other Hours'),
        ),
        migrations.AddField(
            model_name='course',
            name='self_learning_practical',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Self-Learning Project/Research/Essay/Thesis Hours'),
        ),
        migrations.AddField(
            model_name='course',
            name='self_learning_study',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Self-Learning Study Hours'),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='self_learning_assignments',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Self-Learning Assignments Hours'),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='self_learning_library',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Self-Learning Library Hours'),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='self_learning_other',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Self-Learning Other Hours'),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='self_learning_practical',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Self-Learning Project/Research/Essay/Thesis Hours'),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='self_learning_study',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Self-Learning Study Hours'),
        ),
    ]
