= Feasibility Study for Course Specification
Information & Communications Technology Center (ICTC), KFUPM
Version 1.0, 20 March 2019: First version

include::includes/proprietary-information.adoc[]

[discrete]
== Document Classification
Internal

[discrete]
== Version History

[cols="1,3,1,4",options="header",small]
|==================================================
| Version | Author(s) | Date      | Change
| 1.0     | Saeed Alsowail  <alsowail@kfupm.edu.sa> |  2019-03-20 | First version
|==================================================

<<<

== Client Information

. Who are the client representatives that were contacted to fill-in this
document?
+
|==================================================
| Name | Title | Department | Email | Phone(s)
| Dr. Anas Al-Rabeei | |Academic Assessment Center |roubaiey@kfupm.edu.sa |8959
|==================================================

. Who will actually sign-off the requirements and overall request?
+
|==================================================
| Name | Title | Department | Email | Phone(s)
|Dr. Saad Al-Abeedi |Director |Academic Assessment Center |alabeedi@kfupm.edu.sa |7833
|==================================================

. Who is the Subject Matter Expert (SME)?
+
|==================================================
| Name | Title | Department | Email | Phone(s)
| Dr. Anas Al-Rabeei | |Academic Assessment Center |roubaiey@kfupm.edu.sa |8959
|==================================================

. Who will be the end users?
+
.. Faculty members
.. Chairmen of the curriculum management committees
.. Deanship of academic development staff


== Client Needs

The client needs a system that digitizes the course specification template, so all the data related to the course specification can be reused by other systems and reports. In addition,the process of approving and reviewing course specification has to be implemented in this system. However, in the first version of the system, only the first part of the approval process will be implemented. This covers the submission of the course specification by faculty members and the approval of the curriculum committee chairman of the corresponding academic department.

Examples of systems and reports  that will use the course specification data include the course file system, course report, course syllabus, course outcome assessment report, and the assessment/accreditation system (Adaa). The course specification details for any course should be prepared to be exported as a document in given format.

== Client Requirements

=== Data requirements
* There may be a need to access books information from Sierra or using the APIs of publishers.

=== Access requirements

. User categories that can access the application
.. Faculty members
.. Chairmen of the curriculum management committees
.. Deanship of academic development staff

=== Is the business process already defined and documented?
- [x] Yes


=== Security requirements
* No special requirements

=== Storage requirements
* No special requirements

=== Frequency of usage
* The system can be used anytime around the year

=== Expected number of concurrent users
* Few faculty members will access the system concurrently

== Client Expectations

The client expects that all the data captured by the system can be reused by other systems. This will reduce the effort currently required from faculty members to enter the same details in multiple places for different purposes.


== Related Systems and Integrations

. Is the request related to any existing system(s)?
* No

. Is there any specific preference of the client regarding the application to be
used? e.g. E-Business, Banner, or any other existing system.
* No

. Will the solution involve integration or data exchange with other
applications?
.. Authentication service
.. E-Business to determine the basic information of the user (name and academic department)
.. Adwar to determine the chainman of the curriculum committee.
.. In the future, an integration will be needed to the academic programs management system (this system does not exist now!)
.. Several systems are expected to read data from this system (including Banner).

== Constraints

. When does the client need the solution to be delivered?
+
Expected date: End of April 2019

CAUTION: The system has been already announced to the academic departments. 

. Is there any _binding_ deadline for request completion, such as
already scheduled launch event?

- [x] Yes. 
* Event name: ABET Accreditation.
* Event date: September 1, 2019

CAUTION: The client expects that both the course specification and the course file systems to be already utilized by the university by December 2019.


. Are there any limitations regarding the environment in which the application
will be deployed?
* No

. Any other constraints.
* The system should be scalable enough to implement the remaining parts of the approval  and review processes, which will not be covered in the first version of the system.


== Recommendations and Justifications

=== Existing vs. New System

.Recommendation

- [ ] Use an existing satellite system
- [ ] Use an existing enterprise system
- [ ] Develop a new solution

- [x] Procurement/Acquisition of a specialized curriculum management software.

.Justification

. A specialized curriculum management software will provide the functionality requested by the client, including other elements that are expected to be requested soon by the client in order to have full implementation of the accreditation and assessment process, which is the ultimate objective of the client. This will cover:
.. Full management of academic programs (including the approval process and the management of review cycles).
.. Courses will be managed as components of academic programs. All prerequisites and co-requisites relationships will be automatically handled by the software.
. Integration with Banner system will be part of the implementation scope.
. If a decision is made to develop the remaining parts of Adaa locally after completing this system, it is expected that several resources will be occupied by the project for long periods of time. 



=== System Recommendations

.Recommendation

* CourseLeaf 
* Kuali Curriculum Management
* FenixEdu

.Justification

Any one of the above can provide the requested functionality. More time is needed to make a final decision.

